### ISSUE TITLE
IO1EN, IO2EN, PS, MS signals do not have pull up resistors

### ISSUE THREAD

**Issue by Sgw32** [hbekel/MixSID#1]
Hi, 

I am working on my MixSIDs and I've found that my GALs are normally level-LOW at these pins. This causes logic of GAL to work incorrect, because it is assumed that we short these signals to GND. 
So, the proposed solution is to add pull-up resistors to these lines.

Best regards,
Fedor.

**Comment by hbekel** [comment]
What kind of GALs are you using? The original Lattice GAL16V8 and the currently available Atmel ATF16V8B I ship have active internal pull-ups, thus no external pull-ups were added to the board.

**Comment by Sgw32** [comment]
According to the logo, they are from Lattice. Anyway they can be counterfeit since they are ordered from some Chinese supplier. Anyway, adding SMD pads for pull-ups is a good option. I can do it and add a merge request, if you want.

**Comment by hbekel** [comment]
Adding SMD components is out of scope for this project. I also won't add parts to support devices not working as specified.
